#-------------------------------
# General Site Settings
title: I'm Lars
logo: logo.png
description: Lars Gregori Blog

#-------------------------------
# Author Settings
author:
  name: Lars Gregori
  image: 01.png
  say-hello: I’m <strong>Lars</strong>
  bio: Writes about <strong>emerging technologies</strong>, <strong>machine learning</strong>, <strong>programming</strong>, and other things. I 🖤  programming languages. <br/> "There's life on mars" ---- Scooter

#-------------------------------
# Contact links
twitter: https://twitter.com/choas # Add your Twitter handle
github: https://github.com/choas
linkedin: https://linkedin.com/in/lars-gregori
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
#instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
#instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
#google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
